<%@ page import="javax.servlet.*" %>
<%
    String alamat=(String)getServletContext().getAttribute("SITE_ROOT");
%>
<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
	<title> Search </title>
    <link href="<%= alamat %>/css/mainstyle.css" rel="stylesheet"/>
	<link href="<%= alamat %>/css/table.css" rel="stylesheet"/>
    <link href="<%= alamat %>/css/loginPopup.css" rel="stylesheet"/>
    <script src="<%= alamat %>/js/ajaxShop.js" type="text/javascript"></script>
    <script src="<%= alamat %>/js/ajaxLogin.js" type="text/javascript"></script>
	<script src="<%= alamat %>/js/autoGeneratedContent.js" type="text/javascript"></script>
</head>
<body>
	<div id="header">
		<div id="toplogo">
			<a href="<%= alamat %>/index.php/home"><img id="logo" src="<%= alamat %>/gambar_barang/logoruserba.jpg" alt="home"></a>
		</div>
		<div id="logintop">
			<?php
				if ($_SESSION['username'] == null)
				{
			?>
			<a href="#login_popup"><strong>Login</strong></a>
			<br><br>
			<a href="<%= alamat %>/index.php/user/register"><strong>Register</strong></a>
			<?php
				} else {
			?>
			<a href="<%= alamat %>/index.php/user/logout"><strong>Logout</strong></a>
			<br><br>
			<a href="<%= alamat %>/index.php/user"><strong>Profile</strong></a>
            <br><br>
			<p id="welcometext">Welcome, <?php echo $_SESSION['username'] ?></p>
            <a href="<%= alamat %>/index.php/user/cart"><img id="tasbelanja" src="<%= alamat %>/gambar_barang/tasbelanja.jpg" alt="Tas Belanja"></a>        

			<?php
				}
			?>
                        <form action="<%= alamat %>/index.php/barang/cari" method="GET">
                        <p id ="search"><b>Cari Barang:</b>
                        Nama : <input type="text" name="search">
                        Kategori : 
                        <select name="kategori">
                        <option value="">--Pilih--</option>
                        <?php
                        while ($row = mysql_fetch_object($data['listCateg']))
                        {
                        ?>
                        <option value="<?=$row->name;?>"><?=$row->name;?></option>
                        <?php
                        }
                        ?>
                        </select>
                        Harga : <input type="text" name="harga">
                        <input type="submit"><br>
                        <span id="radiobutt">
                        <input type="radio" name="operator" value="L" checked>Less than
                        <input type="radio" name="operator" value="E">Equal to
                        <input type="radio" name="operator" value="G">Greater than
                        </span>
                        </p>
                        </form>
        </div>
                <div id="kategori">
                         <p>
								<span><a href="<%= alamat %>/index.php/barang/cari?search=&kategori=Sembako"><strong>Sembako</strong></a></span>
                                <span><a href="<%= alamat %>/index.php/barang/cari?search=&kategori=Handphone"><strong>Handphone</strong></a></span>
                                <span><a href="<%= alamat %>/index.php/barang/cari?search=&kategori=Peralatan+Listrik"><strong>PeralatanElektronik</strong></a></span>
                                <span><a href="<%= alamat %>/index.php/barang/cari?search=&kategori=Aksesoris+Komputer"><strong>AksesorisKomputer</strong></a></span>
                                <span><a href="<%= alamat %>/index.php/barang/cari?search=&kategori=Perabotan+Rumah"><strong>PerabotanRumah</strong></a></span>
                                <span><a href="<%= alamat %>/index.php/barang/cari?search=&kategori=Alat+Tulis"><strong>AlatTulis</strong></a></span>
                         </p>
                </div>
    </div>
	<div class="basiccontent" id="giantcontent">
<h3> Hasil Pencarian untuk keyword <font color="green"><?=$data['nama_barang'];?></font> </h3>

<div id="table">
<div class="header">
	<span class="kolom satu">Nama Barang</span>
	<span class="kolom dua">Gambar Barang</span>
	<span class="kolom tiga">Harga</span>
	<span class="kolom empat">Stok</span>
	<span class="kolom lima">Jumlah Beli</span>
	<span class="kolom enam">Aksi</span>
</div>
<?php
while($row = mysql_fetch_object($data['barang']))
{
?>
	<div class="baris">
		<span class="kolom satu"><?=$row->nama_barang;?></span>
		<span class="kolom dua"><img id="picsize" src="<%= alamat %>/gambar_barang/<?=$row->gambar;?>"></span>
		<span class="kolom tiga"><?=$row->harga_barang;?></span>
		<?php
		if ($row->jumlah_barang > 0)
		{
		?>
		<span class="kolom empat"><?=$row->jumlah_barang;?></span>
		<span class="kolom lima"><input type="text" name="qty" size="8" id="qty_0" value="0"></span>
		<span class="kolom enam">
        <input type="hidden" name="deskripsi_tambahan" id="deskripsi_tambahan"></input>
		<input type="button" value="Tambah ke Cart" id="beli" onClick="onAddToCart('<%= alamat %>/index.php/barang/addCart', <?=$row->id;?>); return false;">
		</span>
		<?php
		}
		else
		{
		?>
			<span class="kolom empat">Habis</span>
		<?php		
		}
		?>
	</div>
<?php
}
?>
</div>

Halaman : 
<?php
for ($i=0; $i<$data['jmlPage']; $i++)
{
?>
	 <a href="<%= alamat %>/index.php/barang/cari?page=<?=$i;?>&search=<?=$data['nama_barang']?>&kategori=<?=$data['kategori'];?>&harga=<?=$data['harga'];?>&operator=<?=$data['operator'];?>"> <?=$i;?> </a>
<?php
}
?>
	</div>

<div id="login_popup">
    <div id="popup">
    <?=$data['loginView'];?>
</div>
</body>
</html>
